def write_gro(atoms, resname, output_filename, box_size=(10.0, 10.0, 10.0)):
    with open(output_filename, "w") as f:
        f.write(f"File generated by topoMOx for {resname}\n")
        f.write(f"{len(atoms):5d}\n")
        for i, (atom, x, y, z) in enumerate(atoms, start=1):
            x_nm, y_nm, z_nm = x / 10, y / 10, z / 10
            f.write(f"{1:5d}{resname:<5s}{atom:>5s}{i:5d}{x_nm:8.3f}{y_nm:8.3f}{z_nm:8.3f}\n")
        f.write(f"{box_size[0]:10.5f}{box_size[1]:10.5f}{box_size[2]:10.5f}\n")
        f.write("\n")

def format_row(row, identified_metals, hetero):
    atom_type = row['attype']
    if atom_type is None:
        return None
    atom_name = (row['atom'])
    return f"{row['nr']:>5}    {atom_type:<4} {row['resid']:>4}       {row['resname']:>4}   {atom_name:>5}   {row['cg']:>4}  {row['charge']:>12.5f}  {row['mass']:>12.5f}"

def format_bonds_row(row, identified_metals, hetero):
    atom_i = int(row['i'])
    atom_j = int(row['j'])
    if row['i'] in identified_metals:
        atom_i = f"{atom_i}P"
    elif row['i'] in hetero:
        atom_i = str(atom_i)
    if row['j'] in identified_metals:
        atom_j = f"{atom_j}P"
    elif row['j'] in hetero:
        atom_j = str(atom_j)
    return f"{atom_i:>5} {atom_j:>5} {int(row['n']):>3} {row['distance']:>10.5f} {row['kb']:>10.1f}"

def format_angles_row(row, identified_metals, hetero):
    atom_i = int(row['i'])
    atom_j = int(row['j'])
    atom_k = int(row['k'])
    if row['i'] in identified_metals:
        atom_i = f"{atom_i}P"
    elif row['i'] in hetero:
        atom_i = str(atom_i)
    if row['j'] in identified_metals:
        atom_j = f"{atom_j}P"
    elif row['j'] in hetero:
        atom_j = str(atom_j)
    if row['k'] in identified_metals:
        atom_k = f"{atom_k}P"
    elif row['k'] in hetero:
        atom_k = str(atom_k)
    return f"{atom_i:>4}  {atom_j:>6}  {atom_k:>6}  {int(row['n']):>3}  {row['angle']:>7.3f}   {row['k_theta']:>7.1f}"
